// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrEpYZfmpr8p6c-Cqz3R81s_kMcdXF8lU',
    appId: '1:792506100139:web:36e35bfcaca554953a0aee',
    messagingSenderId: '792506100139',
    projectId: 'baseauth-af2b3',
    authDomain: 'baseauth-af2b3.firebaseapp.com',
    storageBucket: 'baseauth-af2b3.appspot.com',
    measurementId: 'G-TWVNP0E2P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC2z-L1BjUPCqEaAzvk1_5hpQXivuJIOI',
    appId: '1:792506100139:android:a706cb91b1fb83203a0aee',
    messagingSenderId: '792506100139',
    projectId: 'baseauth-af2b3',
    storageBucket: 'baseauth-af2b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYg-1M9o3Wx-1h34GgQ7h_e3UsPePcxqE',
    appId: '1:792506100139:ios:0cb8ad760812fe7b3a0aee',
    messagingSenderId: '792506100139',
    projectId: 'baseauth-af2b3',
    storageBucket: 'baseauth-af2b3.appspot.com',
    iosBundleId: 'com.example.baseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYg-1M9o3Wx-1h34GgQ7h_e3UsPePcxqE',
    appId: '1:792506100139:ios:0cb8ad760812fe7b3a0aee',
    messagingSenderId: '792506100139',
    projectId: 'baseauth-af2b3',
    storageBucket: 'baseauth-af2b3.appspot.com',
    iosBundleId: 'com.example.baseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrEpYZfmpr8p6c-Cqz3R81s_kMcdXF8lU',
    appId: '1:792506100139:web:e6672ebf2134a1fd3a0aee',
    messagingSenderId: '792506100139',
    projectId: 'baseauth-af2b3',
    authDomain: 'baseauth-af2b3.firebaseapp.com',
    storageBucket: 'baseauth-af2b3.appspot.com',
    measurementId: 'G-7Z2FDBWK8M',
  );
}
